### ISSUE TITLE
Error uploading dashboard to Elasticsearch 6.x

### ISSUE THREAD

**Issue by jgbarah** [chaoss/grimoirelab-kidash#5]
Hi,

I've saved a dashboard from Kibiter 6.1.0-2, using kidash --export. When trying to upload again that dashboard to a new instance of Elasticsearch, I get:

```
$ kidash --import ~/src/jgbarah-grimoire/overview.json 
Traceback (most recent call last):
  File "/tmp/gl/bin/kidash", line 77, in <module>
    ARGS.data_sources, ARGS.add_vis_studies)
  File "/tmp/gl/lib/python3.5/site-packages/kidash/kidash.py", line 703, in import_dashboard
    feed_dashboard(dashboard, elastic_url, es_index, data_sources, add_vis_studies)
  File "/tmp/gl/lib/python3.5/site-packages/kidash/kidash.py", line 720, in feed_dashboard
    dashboard['dashboard']['value'], data_sources, add_vis_studies)
  File "/tmp/gl/lib/python3.5/site-packages/kidash/kidash.py", line 230, in import_item_json
    item_json = fix_dashboard_heights(item_json)
  File "/tmp/gl/lib/python3.5/site-packages/kidash/kidash.py", line 123, in fix_dashboard_heights
    if panel['size_y'] == 1:
KeyError: 'size_y'
```

This is with the most recent kidash, 0.4.2.

Find attached `dashboard.json` (as I said, exported from Kibiter via kidash): [overview.json.gz](https://github.com/chaoss/grimoirelab-kidash/files/1683590/overview.json.gz)

**Comment by acs** [comment]
First, time to reproduce it. I will use `kidash` directly from master.

* Exporting a dashboard from `bitergia/kibiter:6.1.0` docker image based service:

`(acs@dellx) (master % u=) ~/devel/grimoirelab-kidash-fork-acs $ PYTHONPATH=. bin/kidash --export /tmp/overview.json --dashboard Overview`

* Importing this dashboard:

```
(acs@dellx) (master % u=) ~/devel/grimoirelab-kidash-fork-acs $ PYTHONPATH=. bin/kidash --import /tmp/overview.json 
2018-02-01 03:16:40,887 Dashboard Overview imported
```

So I can not reproduce in this first try the problem.

I am going to use your exported dashboard to reproduce it.

```
(acs@dellx) (master % u=) ~/devel/grimoirelab-kidash-fork-acs $ PYTHONPATH=. bin/kidash --import /tmp/overview.json 
Traceback (most recent call last):
  File "bin/kidash", line 77, in <module>
    ARGS.data_sources, ARGS.add_vis_studies)
  File "/home/acs/devel/grimoirelab-kidash-fork-acs/kidash/kidash.py", line 703, in import_dashboard
    feed_dashboard(dashboard, elastic_url, es_index, data_sources, add_vis_studies)
  File "/home/acs/devel/grimoirelab-kidash-fork-acs/kidash/kidash.py", line 720, in feed_dashboard
    dashboard['dashboard']['value'], data_sources, add_vis_studies)
  File "/home/acs/devel/grimoirelab-kidash-fork-acs/kidash/kidash.py", line 230, in import_item_json
    item_json = fix_dashboard_heights(item_json)
  File "/home/acs/devel/grimoirelab-kidash-fork-acs/kidash/kidash.py", line 123, in fix_dashboard_heights
    if panel['size_y'] == 1:
KeyError: 'size_y'
```

Ok, I am going to fix this case, but I would love to reproduce how this dashboard was created.

After some research, this is for dashboards created in Kibiter 6.1 which uses a different way to define the layout of the visualizations in the dashboard. The format in this case is:

`{'type': 'visualization', 'id': 'git_main_numbers', 'panelIndex': '1', 'gridData': {'h': 2, 'y': 4, 'i': '1', 'w': 4, 'x': 0}, 'title': 'Git', 'version': '6.1.0-2'}`

so instead of using the old layout format:

`{'size_x': 4, 'type': 'visualization', 'col': 1, 'row': 6, 'title': 'Git', 'panelIndex': 1, 'id': 'git_main_numbers', 'size_y': 2}
`
it is using `'gridData': {'h': 2, 'y': 4, 'i': '1', 'w': 4, 'x': 0}` in a specific dictionary inside the visualization. 

Ok, fixing it!
